config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300}
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  validates :username, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
            uniqueness: { case_sensitive: false }, 
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in? 
      flash[:alert] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit 
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
   
    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article was deleted successfully."
    else
      flash[:notice] = "Article could not be deleted."
    end
    redirect_to articles_path
  end

  private 
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article."
      redirect_to @article
    end
  end 

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def index
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render "new"
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 2)
  end

  def index 
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user = User.new
  end

  def edit 
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated."
      redirect_to @user
    else
      render 'edit' 
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up."
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles deleted."
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account."
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div>
  <% @articles.each do |article| %>
    <div>
      <div><%= article.title %></div>
      <div><%= article.description %></div>
      <div>
        <% if article.user %>
          <%= link_to article.user.username, user_path(article.user) %>
        <% end %>
      </div>
      <div>
        <%= link_to 'Show',  article_path(article)  %>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <%= link_to 'Edit',  edit_article_path(article)  %>
          <%= link_to 'Delete',  article_path(article), method: :delete, data: {confirm: "Are you sure?"}  %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %>
    <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <br/>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'cancel edit and return to articles listing',  articles_path %>

app/views/articles/index.html.erb
<h1>Articles Listing page</h1>

<%= will_paginate @articles %>
<%= render 'article' %>

<% if logged_in? %>
  <%= link_to 'Create new article',  new_article_path  %>
<% end %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing',  articles_path %>

app/views/articles/show.html.erb
<h1>Showing Article Details</h1>
<p><strong>Title:</strong> <%= @article.title %></p>
<p><strong>Description</strong> <%= @article.description %></p>
<p><%= link_to gravatar_for(@article.user), user_path(@article.user) %> <strong>by</strong> <%= @article.user.username if @article.user %></p>

<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to 'Edit',  edit_article_path(@article)  %> |
  <%= link_to 'Delete',  article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %> |
<% end %>
<%= link_to 'Return to articles listing',  articles_path %>

app/views/categories/new.html.erb
<h1>Create a new Category</h1>

<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category, local: true) do |f| %>
  <p>
    <%= f.label :name, "Category name" %>
    <br/>
    <%= f.text_field :name, placeholder: "Enter a name" %>
  </p>
  <p>
    <%= f.submit class: "btn" %>
  </p>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <p style="color: <%= name == "alert" ? "red" : "green" %>">
    <%= msg %>
  </p>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to 'Home page',  root_path %> |
<%= link_to 'Bloggers',  users_path %> | 
<%= link_to 'Articles',  articles_path %> |
<%= link_to 'About Page',  about_path %> | 
<% if logged_in? %>
  <%= "(Admin)" if current_user.admin? %> <%= link_to current_user.username, user_path(current_user) %> |
  <%= link_to 'Log out', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Sign up!',  signup_path %> |
  <%= link_to 'Log in', login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to 'Articles Listing',  articles_path %> | 
<%= link_to 'Home page',  root_path %>

app/views/pages/home.html.erb
<h1>Home page</h1>
<%= link_to 'Articles Listing',  articles_path %> | 
<%= link_to 'About Page',  about_path %> | 
<%= link_to 'Sign up!',  signup_path %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved</h2>
  <ul>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, local: true) do |f| %>
  <p>
    <%= f.label :username %>
    <br/>
    <%= f.text_field :username, placeholder: "Enter username" %>
  </p>
  <p>
    <%= f.label :email %>
    <br/>
    <%= f.text_field :email, placeholder: "Enter email" %>
  </p>
  <p>
    <%= f.label :password %>
    <br/>
    <%= f.password_field :password, placeholder: "Choose a password" %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? "Sign Up" : "Update Account", class: "btn") %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Alpha Bloggers</h1>
<%= will_paginate @articles %>
<div>
  <% @users.each do |user| %>
    <p>
      <%= link_to user.username, user %>
      <div><%= link_to gravatar_for(user, size: 150), user %></div>
      <div><%= pluralize(user.articles.count, "article") %></div>
      <div>
        <%= link_to 'View Profile',  user_path(user)  %>
        <% if logged_in? %> 
          <% if user == current_user %>
            <%= link_to 'Edit Profile',  edit_user_path(user)  %>
          <% end %>
          <% if current_user.admin? %>
            <%= link_to 'Delete User',  user_path(user), method: :delete, 
            data: {confirm: "Are you sure you want to delete the user account and all associated articles?"}  %>
          <% end %>
        <% end %>
      </div>
      <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
    </p>
  <% end %>
</div>
<%= will_paginate @users %>

app/views/users/new.html.erb
<h1>Sign up for Alpha Blog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>
<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <%= link_to "Edit your profile", edit_user_path(@user) %>
  <%= link_to "Delete profile", user_path(@user), method: :delete, data: { confirm: 'are you sure?'} %>
<% end %>

<h3>Articles</h3>

<%= will_paginate @articles %>
<%= render 'articles/article' %>
<%= will_paginate @articles %>